version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        environment:
            - APP_ENV=dev
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - "8082:80"
        volumes:
            - .:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
