version: '3.8'
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        environment:
            - APP_ENV=dev
            - REDIS_DSN=redis://redis:6379
        depends_on:
            - redis
        networks:
            - app-network

    nginx:
        image: nginx:latest
        ports:
            - "8082:80"
        volumes:
            - .:/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - app-network

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
