# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Application\Handler\Search\AirArabiaFlightSearchHandler:
        tags:
            - { name: 'app.flight_search_handler', provider: 'airarabia' }

    App\Application\Handler\Price\AirArabiaFlightPriceHandler:
        tags:
            - { name: 'app.flight_price_handler', provider: 'airarabia' }

    App\Infrastructure\Client\AirArabia\AirArabiaRestClient:
        arguments:
            $authUrl: '%env(AIRARABIA_AUTH_URL)%'
            $searchUrl: '%env(AIRARABIA_SEARCH_URL)%'
            $login: '%env(AIRARABIA_LOGIN)%'
            $password: '%env(AIRARABIA_PASSWORD)%'
            $agentCode: '%env(AIRARABIA_AGENTCODE)%'
            $posCountry: '%env(AIRARABIA_POS_COUNTRY)%'
            $posStation: '%env(AIRARABIA_POS_STATION)%'
            $currencyCode: '%env(AIRARABIA_CURRENCY)%'

    App\Infrastructure\Client\AirArabia\AirArabiaSoapClient:
        arguments:
            $wsdl: '%env(resolve:AIRARABIA_SOAP_WSDL)%'
            $username: '%env(AIRARABIA_USERID)%'
            $password: '%env(AIRARABIA_PASSWORD)%'
            $requestorId: '%env(AIRARABIA_AGENTCODE)%'
            $terminalId: 'TestUser/Test Runner'

    App\Application\Factory\FlightHandlerFactory:
        arguments:
            $searchHandlers: [ ]
            $priceHandlers: [ ]
        tags: [ kernel.compiler_pass ]
